name: push

on:
  push:
    branches-ignore:
      - "main"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Helm lint and template
        run: |
          helm lint ./charts/sec-policies
          helm template sec-policies ./charts/sec-policies
    
      - name: Bump version
        id: bump_version 
        run: |
          echo "Install semver"
          npm install semver
          ls -la $(pwd)/node_modules/semver/bin/
          export SEMVER_BIN=$(pwd)/node_modules/semver/bin/semver.js
          $SEMVER_BIN
          echo "semver installed: $SEMVER_BIN"
          export CHART_FILE="charts/sec-policies/Chart.yaml"
          export CURRENT_VERSION=$(yq e '.version' "$CHART_FILE")
          COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B | head -1)
          
          if [[ "$COMMIT_MESSAGE" == *"feat(major)"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i major "$CURRENT_VERSION")
          elif [[ "$COMMIT_MESSAGE" == *"feat"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i minor "$CURRENT_VERSION")
          else
            NEW_VERSION=$($SEMVER_BIN bump -i patch "$CURRENT_VERSION")
          fi
          echo $CHART_FILE $CURRENT_VERSION $COMMIT_MESSAGE $NEW_VERSION