name: push

on:
  push:
    branches-ignore:
      - "main"

# Fixes CKV2_GHA_1 by locking down top-level defaults
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Helm lint and template
        run: |
          helm lint ./charts/sec-policies
          helm template sec-policies ./charts/sec-policies
    
      - name: Bump version
        id: bump_version 
        run: |
          echo "Install semver"
          npm install semver
          ls -la $(pwd)/node_modules/semver/bin/
          export SEMVER_BIN=$(pwd)/node_modules/semver/bin/semver.js
          $SEMVER_BIN
          echo "semver installed: $SEMVER_BIN"
          export CHART_FILE="charts/sec-policies/Chart.yaml"
          export CURRENT_VERSION=$(yq e '.version' "$CHART_FILE")
          COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B | head -1)
          
          if [[ "$COMMIT_MESSAGE" == *"feat(major)"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i major "$CURRENT_VERSION")
          elif [[ "$COMMIT_MESSAGE" == *"feat"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i minor "$CURRENT_VERSION")
          else
            NEW_VERSION=$($SEMVER_BIN bump -i patch "$CURRENT_VERSION")
          fi
          echo $CHART_FILE $CURRENT_VERSION $COMMIT_MESSAGE $NEW_VERSION
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@a7683e7b72a04503521247973281ec8142e1ac1f # v12.3112.0
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli
          output_file_path: console