name: push-main

on:
  push:
    branches:
      - "main"

# Fixes CKV2_GHA_1 by locking down top-level defaults
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Helm lint and template
        run: |
          helm lint ./charts/sec-policies
          helm template sec-policies ./charts/sec-policies

      - name: Bump version
        id: bump_version 
        run: |
          echo "Install semver"
          npm install semver
          ls -la $(pwd)/node_modules/semver/bin/
          export SEMVER_BIN=$(pwd)/node_modules/semver/bin/semver.js
          $SEMVER_BIN
          echo "semver installed: $SEMVER_BIN"
          export CHART_FILE="charts/sec-policies/Chart.yaml"
          export CURRENT_VERSION=$(yq e '.version' "$CHART_FILE")
          COMMIT_MESSAGE=$(git log --no-merges -1 --pretty=%B | head -1)
          
          if [[ "$COMMIT_MESSAGE" == *"feat(major)"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i major "$CURRENT_VERSION")
          elif [[ "$COMMIT_MESSAGE" == *"feat"* ]]; then
            NEW_VERSION=$($SEMVER_BIN bump -i minor "$CURRENT_VERSION")
          else
            NEW_VERSION=$($SEMVER_BIN bump -i patch "$CURRENT_VERSION")
          fi
          echo $CHART_FILE $CURRENT_VERSION $COMMIT_MESSAGE $NEW_VERSION
          yq e -i ".version = \"$NEW_VERSION\"" "$CHART_FILE"
          yq e -i ".appVersion = \"$NEW_VERSION\"" "$CHART_FILE"
          echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
          echo "CHART_NAME=$CHART_NAME" >> "$GITHUB_ENV"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_ENV"

      - name: commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add charts/
          # Only commit and push if there are actual differences to avoid workflow failure
          git diff-index --quiet HEAD || (git commit -m "chore: automated file update" && git push)

  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7 # v12.3114.0
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif