name: release

on:
  release:
    types: [ created ]

jobs:
  release-chart:
    runs-on: ubuntu-latest
    environment: 
      name: build-env

    permissions:
      contents: read
      packages: write
      id-token: write

    name: release-chart
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Package chart
        run: helm package ./charts/sec-policies

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin
        
      - name: Push chart
        run: |
          helm push sec-policies-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts